# Python Assignment- Numpy 

Write a function so that the columns of the output matrix are powers of the input 
 vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 
 

In [1]:
import numpy as np
def ATV_matrix(x, N=None, increasing=False):
    """ function will have x the input array, Number of columns in the output. 
    If N is not specified, a square array is returned (N = len(x)).
    increasing =Order of the powers of the columns. 
    If True, the powers increase from left to right, if False (the default) they are reversed."""


    if N==None :
        N= (x.shape[1])
    row=x.shape[0]
    col=x.shape[1]
    arr=np.zeros((col,N))
    if increasing :
        vec= np.stack((np.transpose(x)**(N-i-1) for i in range(N-1,-1,-1 ) ),axis=-1  )
     
    else:
        
        vec=np.stack(([x**(N-i-1) for i in range(N)]),axis=-1)
    return(vec)  
a=np.array([[ 1,  2,  3, 5]])   

print("increasing =True  ")
print(ATV_matrix(a,increasing=True ))
print("increasing =False  ")
print(ATV_matrix(a ))

increasing =True  
[[[  1   1   1   1]]

 [[  1   2   4   8]]

 [[  1   3   9  27]]

 [[  1   5  25 125]]]
increasing =False  
[[[  1   1   1   1]
  [  8   4   2   1]
  [ 27   9   3   1]
  [125  25   5   1]]]


Problem Statement 2: 
 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
 
The moving average sequence has n-k+1 elements as shown below. 
 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
i 1  2  3  4  5  6  7  8  9 10  
===== == == == == == == == == == ==  
Input 10 20 30 40 50 60 70 80 90 100  
y1      25 = (10+20+30+40)/4  
y2      35 = (20+30+40+50)/4  
y3      45 = (30+40+50+60)/4  
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
 
 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and
window of 3. 
 
 

In [2]:
import numpy as np

def mov_avg(x,k):
    print('Input Sequence                       : ',x)
    print('Input window                         : ',k)
    
    seg_arr= x
    seg_len=np.size(seg_arr)
    row_size=seg_len-k+1
    col_size=k
    y=np.zeros((row_size,col_size))
    for i in range(seg_len-k+1):
        y[i]=seg_arr[i:i+k  ]
    print('To Find the Moving Average for below :\n\n')
    print( y)
    mov_avg=np.mean(y,axis=1)   
     
    return(mov_avg)
    

l1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
print("\n\nMoving Average                           : \n\n",mov_avg(l1,k))
    


Input Sequence                       :  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Input window                         :  3
To Find the Moving Average for below :


[[  3.   5.   7.]
 [  5.   7.   2.]
 [  7.   2.   8.]
 [  2.   8.  10.]
 [  8.  10.  11.]
 [ 10.  11.  65.]
 [ 11.  65.  72.]
 [ 65.  72.  81.]
 [ 72.  81.  99.]
 [ 81.  99. 100.]
 [ 99. 100. 150.]]


Moving Average                           : 

 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
